Screen:
    FloatLayout:
        Image:
            source: 'logo_view_maker.png'
        MDLabel:
            text: "Powered By AnuSav"
            font_style: 'H5'
            pos_hint : {'center_x':0.5 ,'center_y':0.15}
            halign :"center"
              
        MDLabel:
            text: "Version 0.1.0"
            font_style: 'H6'
            pos_hint : {'center_x':0.5 ,'center_y':0.1}
            halign :"center"
              
       
       